plugins {
    id 'java'
}

group = 'com.automation'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.17.0'

    // TestNG
    testImplementation 'org.testng:testng:7.9.0'

    // WebDriverManager
    implementation 'io.github.bonigarcia:webdrivermanager:5.6.3'

    // Extent Reports
    implementation 'com.aventstack:extentreports:5.1.1'
}

test {
    useTestNG() {
        suites 'src/test/resources/testng.xml'
    }
}